apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: nginx
  namespace: mytest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-nginx
    spec:
      containers:
       - image: nginx:1.24.0
         name: nginx
